export const queueHead = [
    "Name", "Service", "Fee", "Servicer", "Cycle", "Info"
]

export const queueListDummy = [
    {
        avatar: "https://surgassociates.com/wp-content/uploads/610-6104451_image-placeholder-png-user-profile-placeholder-image-png.jpg",
        name: "Hart Hagerty",
        country: "United States",
        serviceName: "Calculate Median in Excel",
        serviceType: "Task",
        fee: 10,
        status: "Ongoing",
        servicer: "John Doe",
        cycle: "Once",
    },
    {
        avatar: "https://surgassociates.com/wp-content/uploads/610-6104451_image-placeholder-png-user-profile-placeholder-image-png.jpg",
        name: "Brice Swyre",
        country: "China",
        serviceName: "Dailies in Genshin",
        serviceType: "Pilot",
        fee: 23.00,
        status: "Completed",
        servicer: "Mark Zucc",
        cycle: "Daily",
    },
    {
        avatar: "https://surgassociates.com/wp-content/uploads/610-6104451_image-placeholder-png-user-profile-placeholder-image-png.jpg",
        name: "Marjy Ferencz",
        country: "Russia",
        serviceName: "Center a div in html",
        serviceType: "Task",
        fee: 5,
        status: "Pending",
        servicer: "John Raze",
        cycle: "Once",
    },
    {
        avatar: "https://surgassociates.com/wp-content/uploads/610-6104451_image-placeholder-png-user-profile-placeholder-image-png.jpg",
        name: "Yancy Tear",
        country: "Brazil",
        serviceName: "Rank boost in ML",
        serviceType: "Pilot",
        fee: 30,
        status: "Completed",
        servicer: "Primo Uno",
        cycle: "Once",
    },{
        avatar: "https://surgassociates.com/wp-content/uploads/610-6104451_image-placeholder-png-user-profile-placeholder-image-png.jpg",
        name: "Marjy Ferencz",
        country: "Russia",
        serviceName: "Center a div in html",
        serviceType: "Task",
        fee: 5,
        status: "Pending",
        servicer: "John Raze",
        cycle: "Once",
    },{
        avatar: "https://surgassociates.com/wp-content/uploads/610-6104451_image-placeholder-png-user-profile-placeholder-image-png.jpg",
        name: "Brice Swyre",
        country: "China",
        serviceName: "Dailies in Genshin",
        serviceType: "Pilot",
        fee: 23.00,
        status: "Completed",
        servicer: "Mark Zucc",
        cycle: "Daily",
    },
];