import { AVATAR_PLACEHOLDER } from "@/const/app";

export const queueHead = [
  "Name",
  "Service",
  "Fee",
  "Servicer",
  "Cycle",
  "Info",
];

export const queueListDummy = [
  {
    avatar: AVATAR_PLACEHOLDER,
    name: "Hart Hagerty",
    country: "United States",
    serviceName: "Calculate Median in Excel",
    serviceType: "Task",
    fee: 10,
    status: "Ongoing",
    servicer: "John Doe",
    cycle: "Once",
  },
  {
    avatar: AVATAR_PLACEHOLDER,
    name: "Brice Swyre",
    country: "China",
    serviceName: "Dailies in Genshin",
    serviceType: "Pilot",
    fee: 23.0,
    status: "Completed",
    servicer: "Mark Zucc",
    cycle: "Daily",
  },
  {
    avatar: AVATAR_PLACEHOLDER,
    name: "Marjy Ferencz",
    country: "Russia",
    serviceName: "Center a div in html",
    serviceType: "Task",
    fee: 5,
    status: "Pending",
    servicer: "John Raze",
    cycle: "Once",
  },
  {
    avatar: AVATAR_PLACEHOLDER,
    name: "Yancy Tear",
    country: "Brazil",
    serviceName: "Rank boost in ML",
    serviceType: "Pilot",
    fee: 30,
    status: "Completed",
    servicer: "Primo Uno",
    cycle: "Once",
  },
  {
    avatar: AVATAR_PLACEHOLDER,
    name: "Marjy Ferencz",
    country: "Russia",
    serviceName: "Center a div in html",
    serviceType: "Task",
    fee: 5,
    status: "Pending",
    servicer: "John Raze",
    cycle: "Once",
  },
  {
    avatar: AVATAR_PLACEHOLDER,
    name: "Brice Swyre",
    country: "China",
    serviceName: "Dailies in Genshin",
    serviceType: "Pilot",
    fee: 23.0,
    status: "Completed",
    servicer: "Mark Zucc",
    cycle: "Daily",
  },
];
