import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { APP_NAME } from "@/const/app";
import "./globals.css";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="emerald" lang="en">
      <body className={workSans.className}>{children}</body>
    </html>
  );
}
